#local profile
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/testDB2?serverTimezone=UTC
    username: user
    password: useruser
    driver-class-name: com.mysql.cj.jdbc.Driver